/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Not Found error
 */
export type ApiErrorInvalidInputData = {
    status: number;
    error: string;
};

/**
 * Not Found error
 */
export class ApiErrorInvalidInput extends Error {
    status: number;
    error: string;

    /** The original data that was passed to this error instance. */
    data$: ApiErrorInvalidInputData;

    constructor(err: ApiErrorInvalidInputData) {
        super("");
        this.data$ = err;

        this.status = err.status;
        this.error = err.error;

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "ApiErrorInvalidInput";
    }
}

/** @internal */
export namespace ApiErrorInvalidInput$ {
    export const inboundSchema: z.ZodType<ApiErrorInvalidInput, z.ZodTypeDef, unknown> = z
        .object({
            status: z.number().int(),
            error: z.string(),
        })
        .transform((v) => {
            return new ApiErrorInvalidInput(v);
        });

    export type Outbound = {
        status: number;
        error: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApiErrorInvalidInput> = z
        .instanceof(ApiErrorInvalidInput)
        .transform((v) => v.data$)
        .pipe(
            z.object({
                status: z.number().int(),
                error: z.string(),
            })
        );
}
