/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteOrderRequest = {
    /**
     * ID of the order that needs to be deleted
     */
    orderId: number;
};

/** @internal */
export namespace DeleteOrderRequest$ {
    export const inboundSchema: z.ZodType<DeleteOrderRequest, z.ZodTypeDef, unknown> = z.object({
        orderId: z.number().int(),
    });

    export type Outbound = {
        orderId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteOrderRequest> = z.object({
        orderId: z.number().int(),
    });
}
