/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteUserRequest = {
    /**
     * The name that needs to be deleted
     */
    username: string;
};

/** @internal */
export namespace DeleteUserRequest$ {
    export const inboundSchema: z.ZodType<DeleteUserRequest, z.ZodTypeDef, unknown> = z.object({
        username: z.string(),
    });

    export type Outbound = {
        username: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteUserRequest> = z.object({
        username: z.string(),
    });
}
