/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type FindPetsByTagsRequest = {
    /**
     * Tags to filter by
     */
    tags?: Array<string> | undefined;
};

/** @internal */
export namespace FindPetsByTagsRequest$ {
    export const inboundSchema: z.ZodType<FindPetsByTagsRequest, z.ZodTypeDef, unknown> = z.object({
        tags: z.array(z.string()).optional(),
    });

    export type Outbound = {
        tags?: Array<string> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FindPetsByTagsRequest> =
        z.object({
            tags: z.array(z.string()).optional(),
        });
}
