/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetOrderByIdRequest = {
    /**
     * ID of order that needs to be fetched
     */
    orderId: number;
};

/** @internal */
export namespace GetOrderByIdRequest$ {
    export const inboundSchema: z.ZodType<GetOrderByIdRequest, z.ZodTypeDef, unknown> = z.object({
        orderId: z.number().int(),
    });

    export type Outbound = {
        orderId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetOrderByIdRequest> = z.object({
        orderId: z.number().int(),
    });
}
