/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetUserByNameRequest = {
    /**
     * The name that needs to be fetched. Use user1 for testing.
     */
    username: string;
};

/** @internal */
export namespace GetUserByNameRequest$ {
    export const inboundSchema: z.ZodType<GetUserByNameRequest, z.ZodTypeDef, unknown> = z.object({
        username: z.string(),
    });

    export type Outbound = {
        username: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetUserByNameRequest> = z.object(
        {
            username: z.string(),
        }
    );
}
