/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiResponse = {
    code?: number | undefined;
    type?: string | undefined;
    message?: string | undefined;
};

/** @internal */
export namespace ApiResponse$ {
    export const inboundSchema: z.ZodType<ApiResponse, z.ZodTypeDef, unknown> = z.object({
        code: z.number().int().optional(),
        type: z.string().optional(),
        message: z.string().optional(),
    });

    export type Outbound = {
        code?: number | undefined;
        type?: string | undefined;
        message?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApiResponse> = z.object({
        code: z.number().int().optional(),
        type: z.string().optional(),
        message: z.string().optional(),
    });
}
